package com.example.complaintsystembeta.constants;

public class Constants {

    public static final int RESULT_LOAD_FOR_AUDIO_TO_TEXT = 8008;
    public static final int RESULT_LOAD_FOR_IMAGES_FOR_PROVE = 1001;
    public static final String ALL_COMPLAINS = "ALL";
    public static final String NEW_COMPLAINS = "NEW";
    public static final String NOT_DECIDED = "NOT DECIDED";
    public static final String RESOLVED_COMPLAINS = "RESOLVED";
    public static final String PENDING_COMPLAINS = "PENDING";
    public static final String EMPLOYEE_COMPLAINS = "EMPLOYEE";
    public static final String COMPLAINS_NEW = "REGISTERED";
    public static final String COMPLAINS_RESOLVED = "RESOLVED";
    public static final String COMPLAINS_PENDING = "INITIATED";
    public static final String ENGINEERING = "Engineering";
    public static final String ADMINISTRATION = "Admin";
    public static final String ACCOUNT = "Accounts";
    public static final String REVENUE = "Revenue";
    public static final String TECHNICAL = "Technical";
    public static final String SANITATION = "Sanitation";
    public static final String ENGINA = "Engina";
    public static final String FILTERS_ANALYTICS = "Apply filters";
    public static final String URL_IMAGES = "http://192.168.43.31:3000/uploads/";
    public static final int RESULT_LOAD_IMG_FOR_FRONT = 9009;
    public static final int RESULT_LOAD_IMG_FOR_BACK = 8008;
    public static final int RESULT_LOAD_IMG_FOR_WASA_BILL = 7007;

    public static final String REPORTING_ID = "reporting_id";
    public static final String FORWARD_TO = "forward_to";
    public static final String FORWARD_FROM = "forward_from";
    public static final String REMARKS_BODY = "remarks_body";
    public static final String SUGGEST_DATE = "SUGGEST_DATE";
    public static final String REST_API = "http://192.168.43.31:3000/api/";
    public static final String PREVELDGES_ON_FORWARD = "previldges";
    public static final String ACCOUNT_NUMBER = "cnic";
    public static final String COMPLAIN_FILTER = "complain_filter";
    public static final String NAME = "name";
    public static final String FORWARD_COMPLAINS = "forwarded complains";
    public static final String REPLY_TO_FORWARD = "reply";
    public static final String ONLY_FORWARDED_COMPLAIN_REPORT_SHOW = "only forwarded complians";
    public static final String DESIGNATION_ID = "des";
    public static final String ONLY_FORWARDED_COMPLAIN_SHOW = "only forwarded complians";
    public static final String ADMIN = "admin";
    public static final String USER = "admin";
    public static final String DESIGNATION_TITLE = "designation";
    public static final String NONE = "NONE";
    public static final String IS_REPLY = "reply";
    public static final String IS_CURRENT = "current";
    public static final String COMPLAIN_IN_PROCESS = "IN PROCESS";
    public static final String FORWARD_FROM_NAME_ID_DES = "name with id";
    public static final String COMPLAINS_IN_PROCESS = "IN PROCESS";
    public static final String EMPLOYEE_ID = "employee_id";
    public static final String TAG_DIALOGUE_BOTTOM_SHEET = "BottomSheetDailague";
    public static final int CAMERA = 10001;
    public static final int MY_PERMISSIONS_REQUEST_CAMERA = 10002;
    public static final String STATUS_COMPLAIN = "statusComplain";
    public static final String CHOICE = "ChoiceBetweenToOrFrom";
    public static final String DELAY = "Delay";
    public static final long LOCATION_REFRESH_TIME = 1000;
    public static final float LOCATION_REFRESH_DISTANCE = 20;
    public static final int PERMISSIONS_REQUEST_ENABLE_GPS = 101;
    public static final int PERMISSIONS_REQUEST_ACCESS_FINE_LOCATION = 102;
}
